defmodule Bier.OpenAPI do
  @moduledoc """
  Builds the Swagger 2.0 (OpenAPI 2.0) root document from an introspection
  snapshot. Wire-format match to PostgREST v14.12 is the contract; see
  spec/openapi.yaml and spec/conformance/cases/16*.yaml.
  """

  alias Bier.OpenAPI.Types

  @default_title "PostgREST API"
  @default_description "This is a dynamic API generated by PostgREST"

  @doc """
  Builds the Swagger 2.0 document map from an introspection snapshot.

  Input keys: `:relations`, `:functions`, `:schema_comment`, `:security_active?`,
  `:docs_version`.
  """
  def build(input) do
    {title, desc} = info(input.schema_comment)

    %{
      "swagger" => "2.0",
      "info" => put_optional(%{"title" => title, "version" => "14.12"}, "description", desc),
      "externalDocs" => %{
        "url" => "https://postgrest.org/en/#{input.docs_version}/references/api.html",
        "description" => "PostgREST Documentation"
      },
      "basePath" => "/",
      "paths" => paths(input),
      "definitions" => definitions(input)
    }
    |> with_security(input.security_active?)
  end

  defp info(nil), do: {@default_title, @default_description}
  defp info(comment), do: split_comment(comment)

  defp split_comment(nil), do: {nil, nil}

  defp split_comment(text) do
    case String.split(text, "\n", parts: 2) do
      [only] ->
        {only, nil}

      [head, rest] ->
        {head, rest |> String.replace_leading("\n", "") |> nil_if_empty()}
    end
  end

  defp nil_if_empty(""), do: nil
  defp nil_if_empty(s), do: s

  defp put_optional(map, _k, nil), do: map
  defp put_optional(map, k, v), do: Map.put(map, k, v)

  # Filled in by later tasks (A4/A5); stub keeps the skeleton self-consistent.
  defp paths(_input), do: %{}

  defp definitions(input) do
    Map.new(input.relations, fn rel -> {rel.name, definition(rel)} end)
  end

  defp definition(rel) do
    props = Map.new(rel.columns, fn col -> {col.name, property(col, rel)} end)
    required = for c <- rel.columns, c.notnull?, do: c.name

    %{"type" => "object", "properties" => props}
    |> put_optional("description", rel.comment)
    |> put_required(required)
  end

  defp put_required(map, []), do: map
  defp put_required(map, required), do: Map.put(map, "required", required)

  defp property(col, rel) do
    opts =
      []
      |> maybe_kw(:max_length, col.max_length)
      |> maybe_kw(:enum, col.enum_labels)

    col.type
    |> Types.schema(opts)
    |> put_optional("description", column_description(col, rel))
    |> put_default(Types.default(col.default, col.type))
  end

  defp maybe_kw(kw, _k, nil), do: kw
  defp maybe_kw(kw, k, v), do: Keyword.put(kw, k, v)

  defp put_default(map, :omit), do: map
  defp put_default(map, v), do: Map.put(map, "default", v)

  defp column_description(col, rel) do
    [col.comment, pk_note(col), fk_note(col, rel)]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      parts -> Enum.join(parts, "\n\n")
    end
  end

  defp pk_note(%{pk?: true}), do: "Note:\nThis is a Primary Key.<pk/>"
  defp pk_note(_), do: nil

  defp fk_note(col, rel) do
    case Enum.find(rel.foreign_keys, fn fk -> fk.columns == [col.name] end) do
      %{ref_relation: t, ref_columns: [c]} ->
        "Note:\nThis is a Foreign Key to `#{t}.#{c}`.<fk table='#{t}' column='#{c}'/>"

      _ ->
        nil
    end
  end

  defp with_security(doc, false), do: doc

  defp with_security(doc, true) do
    doc
    |> Map.put("security", [%{"JWT" => []}])
    |> Map.put("securityDefinitions", %{
      "JWT" => %{
        "type" => "apiKey",
        "in" => "header",
        "name" => "Authorization",
        "description" => "Add the token prepending \"Bearer \" (without quotes) to it"
      }
    })
  end
end
