defmodule Bier.OpenAPI do
  @moduledoc """
  Builds the Swagger 2.0 (OpenAPI 2.0) root document from an introspection
  snapshot. Wire-format match to PostgREST v14.12 is the contract; see
  spec/openapi.yaml and spec/conformance/cases/16*.yaml.
  """

  alias Bier.OpenAPI.Types

  @default_title "PostgREST API"
  @default_description "This is a dynamic API generated by PostgREST"

  # Every RPC operation advertises these (procOp produces, OpenAPI.hs#L360).
  @rpc_produces [
    "application/json",
    "application/vnd.pgrst.object+json;nulls=stripped",
    "application/vnd.pgrst.object+json"
  ]

  @doc """
  Builds the Swagger 2.0 document map from an introspection snapshot.

  Input keys: `:relations`, `:functions`, `:schema_comment`, `:security_active?`,
  `:docs_version`, and optionally `:proxy_uri` (openapi-server-proxy-uri).
  """
  def build(input) do
    {title, desc} = info(input.schema_comment)

    %{
      "swagger" => "2.0",
      "info" => put_optional(%{"title" => title, "version" => "14.12"}, "description", desc),
      "externalDocs" => %{
        "url" => "https://postgrest.org/en/#{input.docs_version}/references/api.html",
        "description" => "PostgREST Documentation"
      },
      "basePath" => "/",
      "paths" => paths(input),
      "definitions" => definitions(input),
      "parameters" => parameters(input)
    }
    |> with_security(input.security_active?)
    |> with_proxy(input[:proxy_uri])
  end

  # openapi-server-proxy-uri overrides where the document says the API lives:
  # the URI's scheme/host/path become `schemes`, `host` and `basePath`. The
  # port is appended only when it isn't the scheme default, and an empty path
  # stays the root basePath. The URI was validated at boot (Bier.Config).
  defp with_proxy(doc, nil), do: doc

  defp with_proxy(doc, proxy_uri) do
    uri = URI.parse(proxy_uri)

    host =
      if uri.port && uri.port != URI.default_port(uri.scheme),
        do: "#{uri.host}:#{uri.port}",
        else: uri.host

    Map.merge(doc, %{
      "schemes" => [uri.scheme],
      "host" => host,
      "basePath" => base_path(uri.path)
    })
  end

  defp base_path(path) when path in [nil, ""], do: "/"
  defp base_path(path), do: path

  defp info(nil), do: {@default_title, @default_description}
  defp info(comment), do: split_comment(comment)

  defp split_comment(nil), do: {nil, nil}

  defp split_comment(text) do
    case String.split(text, "\n", parts: 2) do
      [only] ->
        {only, nil}

      [head, rest] ->
        {head, rest |> String.replace_leading("\n", "") |> nil_if_empty()}
    end
  end

  defp nil_if_empty(""), do: nil
  defp nil_if_empty(s), do: s

  defp put_optional(map, _k, nil), do: map
  defp put_optional(map, k, v), do: Map.put(map, k, v)

  defp paths(input) do
    rel_paths = Map.new(input.relations, fn rel -> {"/" <> rel.name, relation_path_item(rel)} end)

    rel_paths
    |> Map.merge(function_paths(input))
    |> Map.put("/", root_path_item())
  end

  # The root introspection entry: GET-only, no parameters, produces the
  # OpenAPI media type pair (makeRootPathItem, OpenAPI.hs#L370-379).
  defp root_path_item do
    %{
      "get" => %{
        "tags" => ["Introspection"],
        "summary" => "OpenAPI description (this document)",
        "produces" => ["application/openapi+json", "application/json"],
        "responses" => %{"200" => %{"description" => "OK"}}
      }
    }
  end

  defp function_paths(input) do
    input.functions
    |> Enum.group_by(& &1.name)
    |> Map.new(fn {name, overloads} ->
      {"/rpc/#{name}", function_path_item(winning_overload(overloads))}
    end)
  end

  # PostgREST sorts a name's overloads ascending by parameter count and the
  # last-inserted path item wins, so the most-parameters overload supplies the
  # entire /rpc/<fn> item (SchemaCache.hs decodeFuncs + Routine Ord;
  # OpenAPI.hs makePathItems fromList). Parameter-count ties fall back to
  # input order (stable sort), approximating PostgREST's full Ord tuple.
  defp winning_overload(overloads) do
    overloads |> Enum.sort_by(&length(&1.in_params)) |> List.last()
  end

  defp function_path_item(fun) do
    {summary, description} = split_comment(fun.comment)
    tags = ["(rpc) #{fun.name}"]

    post =
      %{
        "tags" => tags,
        "produces" => @rpc_produces,
        "parameters" => [
          rpc_body_param(fun, summary, description),
          %{"$ref" => "#/parameters/preferParams"}
        ],
        "responses" => %{"200" => %{"description" => "OK"}}
      }
      |> put_optional("summary", summary)
      |> put_optional("description", description)

    item = %{"post" => post}

    if fun.volatility == :volatile do
      item
    else
      get =
        %{
          "tags" => tags,
          "produces" => @rpc_produces,
          "parameters" => Enum.map(fun.in_params, &rpc_query_param/1),
          "responses" => %{"200" => %{"description" => "OK"}}
        }
        |> put_optional("summary", summary)
        |> put_optional("description", description)

      Map.put(item, "get", get)
    end
  end

  defp rpc_query_param(p) do
    p.type
    |> Types.query_param(variadic: p.variadic?)
    |> Map.merge(%{"name" => p.name, "in" => "query", "required" => rpc_required?(p)})
  end

  defp rpc_body_param(fun, summary, description) do
    props = Map.new(fun.in_params, fn p -> {p.name, Types.schema(p.type, [])} end)
    required = for p <- fun.in_params, rpc_required?(p), do: p.name
    desc = [summary, description] |> Enum.reject(&is_nil/1) |> Enum.join("\n\n") |> nil_if_empty()

    schema =
      %{"type" => "object", "properties" => props}
      |> put_optional("description", desc)
      |> put_required(required)

    %{"name" => "args", "in" => "body", "required" => true, "schema" => schema}
  end

  # A VARIADIC arg or an arg with a DEFAULT is optional; everything else is required.
  defp rpc_required?(p), do: not (p.has_default? or p.variadic?)

  # `:methods` (set by openapi-mode = follow-privileges) trims the advertised
  # operations; nil falls back to the kind default (tables fully writable,
  # views GET-only).
  defp methods(rel), do: rel.methods || default_methods(rel.kind)

  defp default_methods(:table), do: [:get, :post, :patch, :delete]
  defp default_methods(_), do: [:get]

  defp relation_path_item(rel) do
    {summary, description} = split_comment(rel.comment)

    op = fn extra ->
      %{"tags" => [rel.name]}
      |> put_optional("summary", summary)
      |> put_optional("description", description)
      |> Map.merge(extra)
    end

    get =
      op.(%{
        "parameters" =>
          row_filter_refs(rel) ++
            refs(~w(select order range rangeUnit offset limit preferCount)),
        "responses" => %{
          "200" => %{
            "description" => "OK",
            "schema" => %{
              "type" => "array",
              "items" => %{"$ref" => "#/definitions/#{rel.name}"}
            }
          },
          "206" => %{"description" => "Partial Content"}
        }
      })

    methods = methods(rel)

    %{"get" => get}
    |> put_method(
      :post in methods,
      "post",
      op.(%{
        "parameters" => refs(["body.#{rel.name}", "select", "preferPost"]),
        "responses" => %{"201" => %{"description" => "Created"}}
      })
    )
    |> put_method(
      :patch in methods,
      "patch",
      op.(%{
        "parameters" => row_filter_refs(rel) ++ refs(["body.#{rel.name}", "preferReturn"]),
        "responses" => %{"204" => %{"description" => "No Content"}}
      })
    )
    |> put_method(
      :delete in methods,
      "delete",
      op.(%{
        "parameters" => row_filter_refs(rel) ++ refs(["preferReturn"]),
        "responses" => %{"204" => %{"description" => "No Content"}}
      })
    )
  end

  defp put_method(item, false, _verb, _op), do: item
  defp put_method(item, true, verb, op), do: Map.put(item, verb, op)

  defp row_filter_refs(rel) do
    Enum.map(rel.columns, fn c ->
      %{"$ref" => "#/parameters/rowFilter.#{rel.name}.#{c.name}"}
    end)
  end

  defp refs(names), do: Enum.map(names, fn n -> %{"$ref" => "#/parameters/#{n}"} end)

  defp parameters(input) do
    shared = %{
      "select" => %{
        "name" => "select",
        "in" => "query",
        "type" => "string",
        "required" => false,
        "description" => "Filtering Columns"
      },
      "order" => %{
        "name" => "order",
        "in" => "query",
        "type" => "string",
        "required" => false,
        "description" => "Ordering"
      },
      "range" => %{
        "name" => "Range",
        "in" => "header",
        "type" => "string",
        "required" => false,
        "description" => "Limiting and Pagination"
      },
      "rangeUnit" => %{
        "name" => "Range-Unit",
        "in" => "header",
        "type" => "string",
        "required" => false,
        "default" => "items",
        "description" => "Limiting and Pagination"
      },
      "offset" => %{
        "name" => "offset",
        "in" => "query",
        "type" => "string",
        "required" => false,
        "description" => "Limiting and Pagination"
      },
      "limit" => %{
        "name" => "limit",
        "in" => "query",
        "type" => "string",
        "required" => false,
        "description" => "Limiting and Pagination"
      },
      "preferCount" => %{
        "name" => "Prefer",
        "in" => "header",
        "type" => "string",
        "required" => false,
        "enum" => ["count=none"],
        "description" => "Preference"
      },
      "preferPost" => %{
        "name" => "Prefer",
        "in" => "header",
        "type" => "string",
        "required" => false,
        "enum" => [
          "return=representation",
          "return=minimal",
          "return=none",
          "resolution=ignore-duplicates",
          "resolution=merge-duplicates"
        ],
        "description" => "Preference"
      },
      "preferReturn" => %{
        "name" => "Prefer",
        "in" => "header",
        "type" => "string",
        "required" => false,
        "enum" => ["return=representation", "return=minimal", "return=none"],
        "description" => "Preference"
      },
      "preferParams" => %{
        "name" => "Prefer",
        "in" => "header",
        "type" => "string",
        "required" => false,
        "description" => "Preference"
      },
      "on_conflict" => %{
        "name" => "on_conflict",
        "in" => "query",
        "type" => "string",
        "required" => false,
        "description" => "On Conflict"
      }
    }

    row_filters =
      for rel <- input.relations, col <- rel.columns, into: %{} do
        {"rowFilter.#{rel.name}.#{col.name}",
         %{
           "name" => col.name,
           "in" => "query",
           "type" => "string",
           "required" => false
         }
         |> put_optional("description", col.comment)}
      end

    bodies =
      for rel <- input.relations, :post in methods(rel) or :patch in methods(rel), into: %{} do
        {"body.#{rel.name}",
         %{
           "name" => rel.name,
           "description" => rel.name,
           "required" => false,
           "in" => "body",
           "schema" => %{"$ref" => "#/definitions/#{rel.name}"}
         }}
      end

    shared |> Map.merge(row_filters) |> Map.merge(bodies)
  end

  defp definitions(input) do
    Map.new(input.relations, fn rel -> {rel.name, definition(rel)} end)
  end

  defp definition(rel) do
    props = Map.new(rel.columns, fn col -> {col.name, property(col, rel)} end)
    required = for c <- rel.columns, c.notnull?, do: c.name

    %{"type" => "object", "properties" => props}
    |> put_optional("description", rel.comment)
    |> put_required(required)
  end

  defp put_required(map, []), do: map
  defp put_required(map, required), do: Map.put(map, "required", required)

  defp property(col, rel) do
    opts =
      []
      |> maybe_kw(:max_length, col.max_length)
      |> maybe_kw(:enum, col.enum_labels)

    col.type
    |> Types.schema(opts)
    |> put_optional("description", column_description(col, rel))
    |> put_default(Types.default(col.default, col.type))
  end

  defp maybe_kw(kw, _k, nil), do: kw
  defp maybe_kw(kw, k, v), do: Keyword.put(kw, k, v)

  defp put_default(map, :omit), do: map
  defp put_default(map, v), do: Map.put(map, "default", v)

  defp column_description(col, rel) do
    [col.comment, pk_note(col, rel), fk_note(col, rel)]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      parts -> Enum.join(parts, "\n\n")
    end
  end

  defp pk_note(col, rel) do
    if col.name in rel.primary_key, do: "Note:\nThis is a Primary Key.<pk/>", else: nil
  end

  defp fk_note(col, rel) do
    case Enum.find(rel.foreign_keys, fn fk -> fk.columns == [col.name] end) do
      %{ref_relation: t, ref_columns: [c]} ->
        "Note:\nThis is a Foreign Key to `#{t}.#{c}`.<fk table='#{t}' column='#{c}'/>"

      _ ->
        nil
    end
  end

  defp with_security(doc, false), do: doc

  defp with_security(doc, true) do
    doc
    |> Map.put("security", [%{"JWT" => []}])
    |> Map.put("securityDefinitions", %{
      "JWT" => %{
        "type" => "apiKey",
        "in" => "header",
        "name" => "Authorization",
        "description" => "Add the token prepending \"Bearer \" (without quotes) to it"
      }
    })
  end
end
