defmodule Bier.OpenAPI do
  @moduledoc """
  Builds the Swagger 2.0 (OpenAPI 2.0) root document from an introspection
  snapshot. Wire-format match to PostgREST v14.12 is the contract; see
  spec/openapi.yaml and spec/conformance/cases/16*.yaml.
  """

  @default_title "PostgREST API"
  @default_description "This is a dynamic API generated by PostgREST"

  @doc """
  Builds the Swagger 2.0 document map from an introspection snapshot.

  Input keys: `:relations`, `:functions`, `:schema_comment`, `:security_active?`,
  `:docs_version`.
  """
  def build(input) do
    {title, desc} = info(input.schema_comment)

    %{
      "swagger" => "2.0",
      "info" => put_optional(%{"title" => title, "version" => "14.12"}, "description", desc),
      "externalDocs" => %{
        "url" => "https://postgrest.org/en/#{input.docs_version}/references/api.html",
        "description" => "PostgREST Documentation"
      },
      "basePath" => "/",
      "paths" => paths(input),
      "definitions" => definitions(input)
    }
    |> with_security(input.security_active?)
  end

  defp info(nil), do: {@default_title, @default_description}
  defp info(comment), do: split_comment(comment)

  defp split_comment(nil), do: {nil, nil}

  defp split_comment(text) do
    case String.split(text, "\n", parts: 2) do
      [only] ->
        {only, nil}

      [head, rest] ->
        {head, rest |> String.replace_leading("\n", "") |> nil_if_empty()}
    end
  end

  defp nil_if_empty(""), do: nil
  defp nil_if_empty(s), do: s

  defp put_optional(map, _k, nil), do: map
  defp put_optional(map, k, v), do: Map.put(map, k, v)

  # Filled in by later tasks (A3/A4/A5); stubs keep the skeleton self-consistent.
  defp paths(_input), do: %{}
  defp definitions(_input), do: %{}

  defp with_security(doc, false), do: doc

  defp with_security(doc, true) do
    doc
    |> Map.put("security", [%{"JWT" => []}])
    |> Map.put("securityDefinitions", %{
      "JWT" => %{
        "type" => "apiKey",
        "in" => "header",
        "name" => "Authorization",
        "description" => "Add the token prepending \"Bearer \" (without quotes) to it"
      }
    })
  end
end
